[client]
showErrorDetails = true

[logger]
level = "info"

[theme]
primaryColor = "#e87960ff"
backgroundColor = "#0e1117"
secondaryBackgroundColor = "#262730"
textColor = "#fafafa"
font = "sans serif"